# Generated by Django 3.1.7 on 2021-03-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0002_auto_20210317_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_2',
            new_name='Car',
        ),
    ]
