# Generated by Django 3.1.7 on 2021-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0003_auto_20210317_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=30)),
                ('year_released', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Type_of_the_Car',
        ),
    ]
