# Generated by Django 3.1.7 on 2021-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0004_auto_20210318_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
