# Generated by Django 3.1.7 on 2021-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0005_auto_20210318_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
