# Generated by Django 3.1.7 on 2021-03-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0008_auto_20210329_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
