# Generated by Django 3.1.7 on 2021-03-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0009_auto_20210329_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
