# Generated by Django 3.1.7 on 2021-04-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0011_auto_20210329_0622'),
    ]

    operations = [
    ]
