# Generated by Django 3.1.7 on 2021-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0012_auto_20210405_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
