# Generated by Django 3.1.7 on 2021-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0014_auto_20210407_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='imgurl',
            field=models.CharField(default='https://image.shutterstock.com/image-illustration/car-engine-disassembled-many-motor-260nw-1355915309.jpg', max_length=200),
        ),
    ]
